export const countryCodes = [
    { label: '+1 (US/Canada)', value: '+1' },
    { label: '+20 (Egypt)', value: '+20' },
    { label: '+27 (South Africa)', value: '+27' },
    { label: '+30 (Greece)', value: '+30' },
    { label: '+31 (Netherlands)', value: '+31' },
    { label: '+32 (Belgium)', value: '+32' },
    { label: '+33 (France)', value: '+33' },
    { label: '+34 (Spain)', value: '+34' },
    { label: '+39 (Italy)', value: '+39' },
    { label: '+40 (Romania)', value: '+40' },
    { label: '+44 (UK)', value: '+44' },
    { label: '+45 (Denmark)', value: '+45' },
    { label: '+46 (Sweden)', value: '+46' },
    { label: '+47 (Norway)', value: '+47' },
    { label: '+48 (Poland)', value: '+48' },
    { label: '+49 (Germany)', value: '+49' },

    // Châu Á
    { label: '+60 (Malaysia)', value: '+60' },
    { label: '+61 (Australia)', value: '+61' },
    { label: '+62 (Indonesia)', value: '+62' },
    { label: '+63 (Philippines)', value: '+63' },
    { label: '+64 (New Zealand)', value: '+64' },
    { label: '+65 (Singapore)', value: '+65' },
    { label: '+66 (Thailand)', value: '+66' },
    { label: '+81 (Japan)', value: '+81' },
    { label: '+82 (South Korea)', value: '+82' },
    { label: '+84 (Vietnam)', value: '+84' },
    { label: '+86 (China)', value: '+86' },
    { label: '+91 (India)', value: '+91' },
    { label: '+92 (Pakistan)', value: '+92' },
    { label: '+93 (Afghanistan)', value: '+93' },
    { label: '+94 (Sri Lanka)', value: '+94' },

    // Châu Mỹ
    { label: '+52 (Mexico)', value: '+52' },
    { label: '+54 (Argentina)', value: '+54' },
    { label: '+55 (Brazil)', value: '+55' },
    { label: '+56 (Chile)', value: '+56' },
    { label: '+57 (Colombia)', value: '+57' },
    { label: '+58 (Venezuela)', value: '+58' },

    // Trung Đông
    { label: '+90 (Turkey)', value: '+90' },
    { label: '+92 (Pakistan)', value: '+92' },
    { label: '+98 (Iran)', value: '+98' },

    // Châu Phi
    { label: '+211 (South Sudan)', value: '+211' },
    { label: '+212 (Morocco)', value: '+212' },
    { label: '+213 (Algeria)', value: '+213' },
    { label: '+216 (Tunisia)', value: '+216' },
    { label: '+218 (Libya)', value: '+218' },
    { label: '+220 (Gambia)', value: '+220' },
    { label: '+221 (Senegal)', value: '+221' },
    { label: '+222 (Mauritania)', value: '+222' },
    { label: '+223 (Mali)', value: '+223' },
    { label: '+225 (Ivory Coast)', value: '+225' },
    { label: '+230 (Mauritius)', value: '+230' },
    { label: '+234 (Nigeria)', value: '+234' },
    { label: '+250 (Rwanda)', value: '+250' },
    { label: '+254 (Kenya)', value: '+254' },
    { label: '+255 (Tanzania)', value: '+255' },
    { label: '+256 (Uganda)', value: '+256' },
    { label: '+258 (Mozambique)', value: '+258' },

    // Châu Đại Dương
    { label: '+670 (East Timor)', value: '+670' },
    { label: '+672 (Antarctica)', value: '+672' },
    { label: '+673 (Brunei)', value: '+673' },
    { label: '+674 (Nauru)', value: '+674' },
    { label: '+675 (Papua New Guinea)', value: '+675' },
    { label: '+676 (Tonga)', value: '+676' },
    { label: '+677 (Solomon Islands)', value: '+677' },
    { label: '+678 (Vanuatu)', value: '+678' },
    { label: '+679 (Fiji)', value: '+679' },
];